version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github_actions"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "java"

  - package-ecosystem: "docker"
    directory: launchers/connector
    labels:
      - "dependabot"
      - "docker"
    schedule:
      interval: "weekly"
