services:
  edc:
    build:
      context: ./launchers
      dockerfile: Dockerfile
      args:
        RUNTIME: connector-vault
    environment:
      EDC_HOSTNAME: "localhost"
      EDC_PARTICIPANT_ID: "my_participant_id"
      
      WEB_HTTP_PATH: "/api"
      WEB_HTTP_PORT: "11001"
      WEB_HTTP_CONTROL_PATH: "/control"
      WEB_HTTP_CONTROL_PORT: "11002"
      WEB_HTTP_MANAGEMENT_PATH: "/management"
      WEB_HTTP_MANAGEMENT_PORT: "11003"
      WEB_HTTP_PROTOCOL_PATH: "/protocol"
      WEB_HTTP_PROTOCOL_PORT: "11004"
      WEB_HTTP_PUBLIC_PATH: "/public"
      WEB_HTTP_PUBLIC_PORT: "11005"
      WEB_HTTP_VERSION_PATH: "/version"
      WEB_HTTP_VERSION_PORT: "11006"

      EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS: "public-key"
      EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS: "private-key"

      EDC_VAULT_HASHICORP_URL: "http://hashicorp_vault:8200"
      EDC_VAULT_HASHICORP_TOKEN: "root"
      EDC_VAULT_HASHICORP_FOLDER: "edc"

    ports:
      - '11001:11001'
      - '11002:11002'
      - '11003:11003'
      - '11004:11004'
      - '11005:11005'
      - '11006:11006'
    
    depends_on:
      - hashicorp_vault

  hashicorp_vault:
    image: hashicorp/vault:1.18.4
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
