openapi: 3.0.1
info:
  description: merged spec
  title: merged spec
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /v3/contractnegotiations/{id}/approve:
    post:
      description: Approve a pending negotiation
      operationId: approveNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            '*/*': {}
          description: default response
      tags:
      - Manual Negotiation Approval
  /v3/contractnegotiations/{id}/reject:
    post:
      description: Reject a pending negotiation
      operationId: rejectNegotiation
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            '*/*': {}
          description: default response
      tags:
      - Manual Negotiation Approval
components:
  schemas: {}
