name: Build and Publish Maven Artifacts

on:
  push:
    branches: [ main ]
    tags:
      - "*"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.MDS_GH_USER }}
          TOKEN: ${{ secrets.MDS_PAT }}
