name: Build and Publish Docker Images of MDS EDC with EDP extension

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - "*"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase_gh_repo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Generate Docker metadata for EDP Experimental MDS connector
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ steps.lowercase_gh_repo.outputs.lowercase }}/connector-vault-postgresql-edp
          labels: |
            org.opencontainers.image.title=MDS EDC EDP Experimental
            org.opencontainers.image.description=MDS EDC connector with EDP extension for production use.
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push vault postgresql edp image
        uses: docker/build-push-action@v6
        with:
          context: ./launchers
          file: launchers/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.tags }}
          build-args: |
            RUNTIME=connector-vault-postgresql-edp
