name: Publish JsonLD contexts

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'extensions/management-jsonld-context/src/main/resources/document/**'

jobs:
  publish-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: |
          mkdir -p public/context
          
          cp extensions/management-jsonld-context/src/main/resources/document/* public/context/

      - uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
