name: Run Tck and Publish report to GH pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - "*"

jobs:
  tck-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/setup-jdk

      - run: ./gradlew tck > tck.report
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ github.token }}

      - run: cat tck.report

      - run: |
          if [[ "${{ github.ref.type }}" == "tag" ]]; then
            version=${{ github.ref_name }}
          else
            version=latest  
          fi
          
          folder=public/tck/${version}
          mkdir -p ${folder}
          
          cp tck.report ${folder}/

      - uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
